spring.application.name=twitterapi
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/twitterapi
spring.datasource.username=postgres
spring.datasource.password=852456
spring.jpa.hibernate.ddl-auto=update